name: docker

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
  images: "docker.io/klutchell/balena-cli,ghcr.io/klutchell/balena-cli"
  local_tag: localhost:5000/balena-cli:latest

jobs:

  build:
    runs-on: ubuntu-20.04

    services:
      registry:
        image: registry:2.7.1
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.images }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/build-push-action@v2
        with:
          platforms: ${{ env.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.local_tag }}
          cache-to: type=gha,mode=max
          cache-from: |
            type=gha
            ${{ steps.meta.outputs.tags }}
            docker.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
          push: true

      - name: Test functionality
        run: |
          for platform in $(tr ',' '\n' <<< "${{ env.platforms }}") ; do
            docker pull --platform ${platform} ${{ env.local_tag }}
            docker run --rm ${{ env.local_tag }} version
            docker run --rm -e DOCKERD=1 -e "DOCKERD_EXTRA_ARGS=--iptables=false" --privileged ${{ env.local_tag }} docker info
          done

      - uses: docker/login-action@v1
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: akhilerm/tag-push-action@v2.0.0
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        with:
          src: ${{ env.local_tag }}
          dst: |
            ${{ steps.meta.outputs.tags }}

      - uses: peter-evans/dockerhub-description@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: klutchell/balena-cli
